# Generated by Django 5.0.3 on 2024-08-16 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_managers_user_address_user_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Address',
            new_name='address',
        ),
    ]
