# Generated by Django 5.0.3 on 2024-03-05 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_type_alter_restaurant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='Rate',
            field=models.DecimalField(decimal_places=2, max_digits=2, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
