# Generated by Django 5.2 on 2025-04-10 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_brand_address_brand_address_ar_brand_address_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='address_ar',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_en',
        ),
    ]
