# Generated by Django 5.2 on 2025-04-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_brand_address_ar_remove_brand_address_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='ar', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='ar', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='ar', max_length=2),
            preserve_default=False,
        ),
    ]
