# Generated by Django 5.0.3 on 2024-03-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_restaurant_rate'),
    ]

    operations = [

        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Price', models.DecimalField(decimal_places=30, max_digits=30)),
                ('Date_of_creation', models.DateField(auto_now_add=True)),
                ('Descreption', models.TextField()),
                ('sizes', models.TextField()),
            ],
        ),
    ]
