# Generated by Django 5.2 on 2025-04-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_brand_language_category_language_product_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='description',
            new_name='description_ar',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='name',
            new_name='name_ar',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='description_ar',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_ar',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='description_ar',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='name_ar',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='language',
        ),
        migrations.RemoveField(
            model_name='product',
            name='language',
        ),
        migrations.AddField(
            model_name='brand',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_en',
            field=models.CharField(default='x', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(default='x', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(default='x', max_length=255),
            preserve_default=False,
        ),
    ]
