# Generated by Django 5.2 on 2025-04-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_description_brand_description_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='language',
        ),
        migrations.AddField(
            model_name='brand',
            name='city',
            field=models.CharField(default='homs', max_length=255),
            preserve_default=False,
        ),
    ]
