# Generated by Django 5.0.3 on 2024-03-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.TextField(default='https://th.bing.com/th/id/R.572c944b3f16b5b1b03b0245b063872e?rik=xWfUlQJ%2fjLTqeQ&pid=ImgRaw&r=0'),
            preserve_default=False,
        ),
    ]
