# Generated by Django 5.0.3 on 2024-03-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_product_sizes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sizes',
            new_name='size',
        ),
    ]
