# Generated by Django 5.0.3 on 2024-03-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_sizes_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('VerySmall', 'VerySmall'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('VeryLarge', 'VeryLarge')], max_length=255),
        ),
    ]
