# Generated by Django 5.0.3 on 2024-03-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('VS', 'VerySmall'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('VL', 'VeryLarge')], max_length=255),
        ),
    ]
