# Generated by Django 5.0.3 on 2024-03-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('VerySmall', 'VS'), ('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('VeryLarge', 'VL')], max_length=255),
        ),
    ]
