# Generated by Django 5.0.3 on 2024-03-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('VS', 'Very Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('VL', 'Very Large')], max_length=3),
        ),
    ]
