# Generated by Django 5.0.3 on 2024-03-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(choices=[('VS', 'Very Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('VL', 'Very Large')], default='S', max_length=3),
            preserve_default=False,
        ),
    ]
