# Generated by Django 5.0.3 on 2024-03-08 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_category_logo'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='category',
        #     name='logo',
        # ),
    ]
