# Generated by Django 5.0.3 on 2024-03-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_category_logo_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='logo',
            field=models.URLField(default='https://th.bing.com/th/id/OIP.2ZhDKxFY2acBHFv5RHXPsgHaEo?rs=1&pid=ImgDetMain'),
            preserve_default=False,
        ),
    ]
