# Generated by Django 5.0.3 on 2024-03-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_category_logo_category_image'),
    ]

    operations = [
      
    ]
