# Generated by Django 5.0.3 on 2024-05-21 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_remove_category_image_category_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
