# Generated by Django 5.0.3 on 2024-05-21 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
