# Generated by Django 5.0.3 on 2024-05-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
