# Generated by Django 5.0.3 on 2024-05-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_category_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, default='Small', max_length=50, null=True),
        ),
    ]
