# Generated by Django 5.0.3 on 2024-05-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_category_logo_product_images_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Rate',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
