# Generated by Django 5.0.3 on 2024-05-21 19:51

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_product_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Rate',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[base.models.validate_rate]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Rate',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
