# Generated by Django 5.0.3 on 2024-05-22 12:34

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_product_rate_alter_restaurant_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.DecimalField(decimal_places=9, max_digits=19, validators=[base.models.validate_price]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Rate',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[base.models.validate_rate]),
        ),
    ]
