# Generated by Django 5.0.3 on 2024-05-22 12:41

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_alter_product_price_alter_product_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Rate',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, validators=[base.models.validate_rate]),
        ),
    ]
