# Generated by Django 5.0.3 on 2024-05-23 10:22

import base.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_alter_cartitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[base.validations.validate_quantity]),
        ),
    ]
