# Generated by Django 5.0.3 on 2024-08-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_alter_order_item_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order_item',
            new_name='OrderItem',
        ),
    ]
