# Generated by Django 5.0.3 on 2024-08-10 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_rename_order_item_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='prodcut',
            new_name='product',
        ),
    ]
